//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueYou.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuideDetails()
        {
            this.Guide = new HashSet<Guide>();
        }
    
        public int GuideDetails_id { get; set; }
        public Nullable<int> Guide_livetime { get; set; }
        public Nullable<System.DateTime> Guide_jiontime { get; set; }
        public string Guide_language { get; set; }
        public string Guide_job { get; set; }
        public string Guide_tips { get; set; }
        public string Guide_main { get; set; }
        public decimal Guide_charge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guide> Guide { get; set; }
        public virtual GuideDetails GuideDetails1 { get; set; }
        public virtual GuideDetails GuideDetails2 { get; set; }
    }
}
